#!/usr/bin/env bash

if (( $EUID != 0 )); then
    echo "Must be ran as root"
    exit 1
fi

mkdir -p /opt/brave.com
mkdir -p /opt/brave.com/brave
mkdir -p /opt/brave.com/brave-beta
mkdir -p /opt/brave.com/brave-nightly


tee /opt/brave.com/brave/brave-browser <<EOF
#!/usr/bin/env bash
brave-browser "\$@"
EOF
chmod +x /opt/brave.com/brave/brave-browser

tee /opt/brave.com/brave-beta/brave-browser-beta <<EOF
#!/usr/bin/env bash
brave-browser-beta "\$@"
EOF
chmod +x /opt/brave.com/brave-beta/brave-browser-beta
ln -sf /opt/brave.com/brave-beta/brave-browser-beta /opt/brave.com/brave-beta/brave-browser

tee /opt/brave.com/brave-nightly/brave-browser-nightly <<EOF
#!/usr/bin/env bash
brave-browser-nightly "\$@"
EOF
chmod +x /opt/brave.com/brave-nightly/brave-browser-nightly
ln -sf /opt/brave.com/brave-nightly/brave-browser-nightly /opt/brave.com/brave-nightly/brave-browser
